sudo: false
language: node_js
node_js:
- '4'
- '0.12'
notifications:
  slack:
    secure: Z899Ot10LOuLEXN2Ul6nmx6ZqVwIyskQLgp7ccuAgLcO61tvU0LJ8mTaFhbh1ZGWQpEOoVKnUwKD5WgdYUYOz9AeZyoJYAbgYr4bGFyeh5VdY1uEltSlDmocxDB23b1pl26MR2cBHFCXX5h4uPhDl+Xc6jTvk8Stloh7kx2cbwkUuruhR3fxJMU7kOPh3IJRWumxrTvXpLtcd2LCA5F0jhCpzEMpr9KlUO1DF2l9KE+bjKUhdMTVW9Y2pOh85ax09hf18ZvDKCi3Z5LnTa3SKnxqfO1PXezp6gdV/KCPlEN7jKyShLe84ov+ebvC5tf+BKbWfAPvU/G3YWwOEsARK7Cr7Tq+tp+jd6xpF7TFqMs2r1i4SVzjo3jH75CCXR4QVCTyaG1v5epkD0kOfewmEcygVtYekfH3nGLXIjEmiilfd6EHYm/RYmKRhAqpoyfslOJhVja4iOjzwxGJbcBtnRmtTr3vMlSJ5WTdkol03BI+XwzF3/YRLC+CrdNgthTO+6LW/ocllccFJ5U6N8bND/Si4tmmlgbTJ95oKQPalOSnWGGQHKuPqoCaH71TsS0gDZ6wmo0m1XAsKj2WNylxR/6Lb6jDH1GSx/O5kPMeQKhWdCSbNtjKnJ4x471oHc/wOHQz8JRg5mpMNrrZYHEGs9L6K6celSBdbRaRLDNd7sM=
