sudo: false
language: node_js
node_js: stable
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- yarn run lint
- yarn run test
deploy:
  provider: npm
  email: opensource@zlab.co.jp
  api_key:
    secure: lQ1PNqYqDQ5Jv6mUNLZj7VH3Gls366PWvhO1UT4b5nHOi8epG48kSX0NEqz0BeOi7szWc0mLsAgPG02fCQ8JrMIdtQ6q/OFPvsqIt1QWRqbzVioH2JgREDApNRILbYokNElWKCnComD16aeK/lLB+5tL+aIulO6ezu/B5OZU5+hBUYNk44xiHra2Jiv3KeTPniZUdjb8j/A+OUW9osJ/Fo7TOVPH24xXDEPI+4Ik/EkY0AoYtxNNT8GEAoB0xJ25ybTxy4xV2QeWmxoyS0f+wtxb258n/mbGwAi000S+l7fTP6C0MkkywJLuaIiPNZFu9LZG2E+Eu9au+aJslScZhWvJ9MQgCmMCrVb5gFvsWOxsAmv+4OiZU15eI5xm7GDGbxvCfh2qOK9cGQIrbmLJcdvzpKR0qGAjJhThWhFYVnBb23p9Fu0ByrqmMJBGyNrBFLIF2eITJcawyJ1f/f/OTQnmxr91mJfGRTZ3vatsSGCTdnMh1dUx8PLzD/YaLKtsv0WjM72OKe9sH1N2JK2NwwzFyAOGeYWqmDUlp+U4Td3MAJSPAVQFAf+tA4rulbTZjKmASoyBLwkR/gsEBRMgZnFCZlBqSNZlZBn3pfnG9YxHtNaNf+ehD6ddeuD+J7yFmaIUnoKVJ2qaHrBkf5NFLkNqM5DCyqeSb7qcHRznTaw=
  on:
    tags: true
